openapi: 3.0.0
info:
  title: Festival Platform (MVP)
  version: 1.0.0
servers:
  - url: http://localhost:3000/api/v1
paths:
  /events:
    get:
      summary: List events
      parameters:
        - in: query
          name: date
          schema: { type: string }
        - in: query
          name: category
          schema: { type: string }
      responses:
        '200':
          description: OK
  /events/{id}:
    get:
      summary: Get event by id or slug
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        '200': { description: OK }
  /checkout:
    post:
      summary: Simulate a checkout and create an order
      requestBody:
        content:
          application/json: {}
      responses:
        '200': { description: OK }
